### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by balarsen**
Steve, here are a handful of minor cleanups in the examples and a Python wrapper for Lgm_Vector.slerp.

### CODE REVIEW

**Comment by balarsen** [comment]
Steve, here is an OSX readme that Mike and made just now.

**Comment by drsteve** [comment]
The OSX wrapper looks fine, but can I get some clean-up of the SLERP stuff?
1. The docstring example won't execute, needs bracket fixes, imports, print statement output, etc.
2. The examples uses a 3 element Lgm_Vector, but should probably use a 4-element unit quaternion (where the 4th element (the real part) is zero).


Re. the OSX readme... we should poke at the lgmpy on your version if you can't get that to work. Also, might be nice to fix up the typos there. Submit another pull request when that's all covered and I'll merge it in.

**Comment by balarsen** [comment]
I disagree with some of this. You don't SLERP on a quaternion and LGM only operates on vectors.

**Comment by drsteve** [comment]
Lgm_Vectors can be of different lengths, we use a 4-element Lgm_vector when representing quaternions (e.g., for ViewDriftShell stuff and MMS coordinates). And SLERP is the standard interpolation method for quaternions - that's actually what it was developed for (but is usually done for unit quaternions, where the real part is zero, so they look like vectors). It can be done on vectors, but it is *the* standard interpolation method for quaternions.

I've checked the codebase, and I guess we have two different SLERP routines. One is in Lgm_Quat, which operates on unit quaternions; the other is in Lgm_Vec, and operates on unit vectors. So I guess in this case the 3-element vector is appropriate, but they should be unit vectors, per the documentation (and that should be noted in the docstring).

**Pull request closed without merging**
