### PR TITLE
Add Tsyganenko & Andreeva 2016 model

### PR DESCRIPTION
**Pull request by drsteve**
This PR provides a C port of the TA2016 model that can be called in pretty much the same way as any of the other magnetic field models in LGM.

- Adds `Lgm_VecMult` for elementwise product (Hadamard product) of two `Lgm_Vector`s
- Adds all necessary function prototypes
- Provides TA2016 model (valid at R<=15Re)
  - Includes setters
  - Uses separate `Lgm_SetCoeffs_TA16` (similar to TS07) to set model coefficients
  - Model params can be read from Tsyganenko's files (estimation from QD files not built in yet)
  - Falls back to default values if TA files cannot be found or the user requests that the params are calculated from Qin-Denton data
  - Checks for valid X position
- Updates `Makefile.am` (in two folders) to include new sources
- Updates data sources to copy RBF params and SW coeffs to data dir
- Adds example program (`Examples/Bfield/Bcompare.c`)
- Includes regression test (against values verified with Fortran version)

### CODE REVIEW

**Comment by drsteve** [comment]
Does anyone have time to take a quick look at this?

It compiles, passes tests (including a regression test for the new model), and there's a sample program...

@mghenderson64, @Pheosics, @jtniehof, @balarsen ??
Just a quick look over or a local run that uses the TA2016 model would be great...

**Comment by Pheosics** [comment]
@drsteve I can take a look at this today

**Comment by Pheosics** [comment]
I was able to compile, run the suite of tests, and run the sample program on the scheme. I didn't really look at the actual code changes made, so if you would like me to review that as well, let me know.

**Comment by drsteve** [comment]
Thanks! If you've got time to do a quick skim of the code for obvious idiocy on my part that'd be appreciated. I used TA16 with the PTM grid generation yesterday, and no obvious issues so far. I haven't visualized the results yet, but I'm more inclined to merge (since it's functional) and then improve the implementation later as required.

**Comment by drsteve** [comment]
Due to things seeming slow when I was doing some McIlwain L calculations I profiled the code with `callgrind`. It was spending about 14% of the time (in the L calculation) just on sin and cos. Because L involves tracing, there'll be a lot of repeated calls with the same coefficients, just slightly changing the position. It turned out that each call was calculating a couple of ~1200 element arrays with trig functions that only depend on the dipole tilt. For a single call, that's negligible, but for calculating L about 10 times we're looking at 10s of millions of calls and that really hits the speed. That takes us from 14% of time spent in `sincos` to less than 0.1% of time spent there.

So my first cut optimization pulls those values into the `TA16_Info` structure, and checks whether the tilt angle is different than the cached one. If it is, we recalculate the `sDT` and `cDTM1` arrays. If not, as will be the case in tracing, then we re-use them and bring the count in my test case down from ~28 million `sincos` calls to ~100000 calls.

**Comment by drsteve** [comment]
Latest commit caches more variables that only depend on dipole tilt. Everything uncached should now depend on the position being evaluated. It seems that there's also a noticeable amount of overhead in using the LGM vector math routines, so I've simplified that where possible and done the calculations directly on the components.

It's still slow (several times slower than TS04!!), but probably about 40% faster for calculating McIlwain L than before I started trying to optimize.

**Comment by Pheosics** [comment]
@drsteve code looks good. Optimization definitely made it faster

**Pull request merged**
