### PR TITLE
DRAFT: Shabansky fix

### PR DESCRIPTION
**Pull request by mghenderson64**
Changes include:
1) Added Lgm_FluxTubeVolume() to compute V = Integral of 1/|B| from south footpoint to north footpoint. 
2) Added example program using Lgm_FluxTubeVolume.
3) Added a SimpleTrace.c code in Examples
4) Cleaned up dipole test in Examples/LstarDipoleTest_omp. It works.
5) Made extensive changes to drift-shell calculations to improve stability and make the two "I-Search" strategies work.
6) Major change to Lgm_Trace(). This now pre-traces the FL in order to find the global Bmin. The approximate position is then fed into Lgm_TraceToMinBSurf() which then converges to the Bmin. Note that this really should be done in Lgm_TraceToMinBSurf() so that consistent results are obtained between Lgm_TraceToMinBSurf() and Lgm_Trace(). However, it only affects FLs with multiple minima.
7) Some changes to Lgm_KdTree. Added memory managment routines and added some test for defined Objects before trying to access them (some problems dont require Objects, like the DstNN example, but would fail if it wasnt alloced.)
8) Fixed the DstNN example code in Examples/KdTree.

### CODE REVIEW

**Comment by drsteve** [comment]
Thanks @mghenderson64  - the Travis CI is reporting a failure to compile. It looks like Lgm_FluxTubeVolume.c is missing.

If you can commit that to the same branch and push it'll automatically update the pull request and resubmit the tests. Once they've run I'll take a closer look.

**Comment by mghenderson64** [comment]
I haven't pushed any of this yet, but working on it....



  *   There's no Makefile for the FluxTubeVolume example.

Added

  *   The FluxTubeVolume example doesn't compile for me as it doesn't know where to look for the function definition. Is a header file missing?

changed name in .h file to the correct name (had FluxTubeVolume instead of Lgm_FluxTubeVolume)

  *   Travis CI is clearly mis-reporting the outcome of check. I get local failures of a number of tests. Can you run make check locally and inspect the output? My guess is that the algorithm changes would lead us to expect the observed regression test failures. If that's the case the expected results files should be updated.

Looking at these now. Results are close. Possibly IGRF changes or tolerances in BS.

  *   Following the above, I think we still expect the weird Lm/L*/Lm failure, so don't worry about that test.

I figured out what at least a big part of this is due to. I will add those fixes as well...

  *   Examples/SimpleTrace doesn't have a Makefile Seems fine once compiled (but writes more output than I'd expect from an example program...)

Added.

  *   Is it possible for the new while loop in BracketZero to get stuck? Should there be a loop counter or some other check so it can't get stuck?

I will check this.

  *   Why was the Jensen-Cain stuff removed from Lgm_MagModelInfo_Set_MagModel? If it was removed in error can you please put it back (in Lgm_InitMagInfo.c)?

Unintentional, I will add back.

  *   Line 234 of Lgm_Trace.c has a command hidden behind a check for a verbosity setting of -100!! Is this a debug that you're hiding? That you meant to remove? I guess it doesn't really hurt for it to be there, but it's never going to appear with any standard verbosity settings.

Haha. I'll nuke that -- was just for debugging.

  *   The section in Lgm_Trace (used to be line 258) removes a check for the return type in Lgm_TraceToMinBSurf. The changes to Lgm_TraceToMinBSurf.c only add comments about fixing the behaviour that would require this check - the behaviour isn't actually fixed yet. So shouldn't we be keeping this check

Yup. I'll add that back.


________________________________

**Comment by drsteve** [comment]
Hey @mghenderson64 - any luck updating this?
I've just merged an update to IGRF (since the 2020 coefficients are out) into the master branch, so you might want to rebase your branch against master to get the IGRF updates before you update test files, etc.

If you have issues with conflicts, etc. that are causing trouble, let me know and I can try to fix things.

**Comment by drsteve** [comment]
Closing as outdated due to #39 and #40

**Pull request closed without merging**
