### PR TITLE
Lgmpy tests

### PR DESCRIPTION
**Pull request by jtniehof**
The lgmpy tests were failing pretty badly. I mostly loosened test tolerances; I did have to make a substantial change to the EDIP on the T89 tests.

This PR does not fix the Lstar failures (#16), which I don't feel comfortable just smashing.

### CODE REVIEW

**Comment by jtniehof** [comment]
I'm going to take a page from Steve's book in #16 and try the T89 EDIP test in C to see if there's something lurking in the Python.

For the other tests, would it make more sense to tighten the tolerances back up and change the expecteds?

**Comment by drsteve** [comment]
I think changed the expected to what we get from the same test in C makes sense here.

One thing to note is that Lgm_B_T89 and Lgm_B_T89c are different models. T89c should be the one folks use unless they have a *really* good reason to use the other.

**Comment by jtniehof** [comment]
Not planning to rewrite *all* the tests in C, just the one that was way off, and so definitely changing the result there. There is Python code for T89 and T89c, and the test is just T89 (no tests on T89c). Whether, then, it's worth fixing the T89 tests vs. just doing T89c tests is another question....

Question is on the other ones, leave tolerance loose or tighten up and change to the value that's coming out at the moment?

**Comment by drsteve** [comment]
Well, we already have some tests in C (run with make check), but it's limited. I think we really need the Python tests to make sure they give the same as the C, with a secondary aim of making sure that the C is doing the right thing (that's what the C tests should be for).

So I'd tighten the tolerance back up and make sure we get the same as the C.

**Comment by balarsen** [comment]
Sorry for the silence, proposal time phew. I am in favor of whatever
changes to make things happy forward. I wrote most of the tests in the past
and they were largely regression tests as I was developing to see if I
busted something. Moving beyond that is great.

**Comment by jtniehof** [comment]
I know we have the C tests since I set up the framework :)

So what I'm reading here is that, before I start reorganizing the Python, in order to make sure I'm not introducing regressions I need:
1) Port the Python unit tests to C/check
2) Put in the current output values to the C tests (so it's a regression against the C from this point forward)
3) Copy those values as the expected into the Python tests
4) Fix the Python code if it doesn't match

And then I can start the process of actually getting in the functionality I need for the stuff where my period of performance ends in four days. You guys are going to owe me a lot of beers.

**Comment by balarsen** [comment]
Well that would be the best solution. I bet there is a lesser one.

1) Make some additional python tests to match the C tests "Exactly", get
those all happy.
2) Update the existing python tests to pass and use them as regression
3) add more tests in c and python as life allows

**Comment by jtniehof** [comment]
I'm digging in so there will be lots of new commits on this PR (initially just a rebase); will note when things are actually in a shape where I will request a merge.

**Comment by jtniehof** [comment]
Process has started here...there is going to be substantial rebasing here as I basically replace the tolerance-adjusting commits with ones that actually fix things. I figured having the tolerances loosened in one commit and then re-tightened with fixes several commits later is going to be confusing. Anyhow magcoords is done and comments welcome as I go ahead on the rest.

**Comment by jtniehof** [comment]
Working on #6 and will post when ready to pull again.

**Comment by jtniehof** [comment]
Everything is now fixed except for the Hilton/McIlwain from Lstar (and the Lsimple from Lstar as well, but Lsimple is completely untested anyhow.) I'd like to request this be merged because despite the failing tests, fewer tests fail--in particular the L* itself matches the C. I don't see that it's reasonable for me to be able to actually make this all work; I just know not to use the non-L* output from Lstar.

**Comment by jtniehof** [comment]
The Python test should fail (but I don't think it's in the CI). The C also is failing on my machine for the "McIlwain before/after L* difference" and I'm definitely clean, up-to-date on this branch. I still would like it merged, since I think it's an improvement, unless we want to declare before/after should change and we can improvise that as some sort of expected failure.

**Comment by drsteve** [comment]
Okay, I'll merge and hopefully we can beat down the issue soon.
Best guess from here is that something is being changed in the tolerances in the MagModelInfo structure.

**Pull request merged**
